name: core_design_system
description: The core UI design system for Zhixuan Super App
version: 0.0.1
publish_to: 'none'

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

flutter:
  shaders:
    - shaders/aurora_flow.frag
    - shaders/rainbow_flow.frag
    - shaders/crimson_nebula.frag
    - shaders/ocean_glacier.frag
    - shaders/emerald_mist.frag


dev_dependencies:
  flutter_lints: ^3.0.0
