name: feature_profile
description: Profile and Login module for Zhixuan Super App
version: 0.0.1
publish_to: 'none'

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  # 核心依赖：设计系统与网络
  core_design_system:
    path: ../../core/core_design_system
  core_network:
    path: ../../core/core_network
  core_media:
    path: ../../core/core_media
  
  # UI 辅助依赖
  cached_network_image: ^3.3.1
  image_picker: ^1.1.2
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0