name: feature_video
description: TikTok-style short video module for Zhixuan Super App
version: 0.0.1
publish_to: 'none'

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  # 核心依赖
  core_design_system:
    path: ../../core/core_design_system
  core_network:
    path: ../../core/core_network
  core_media:
    path: ../../core/core_media
    
  # 视频处理相关 UI (依赖必须在当前包也声明，因为直接使用了它们的 Widget)
  image_picker: ^1.1.2
  video_editor: ^3.0.0
  cached_network_image: ^3.4.1
  dio: ^5.9.2
  path_provider: ^2.1.5
  flutter_riverpod: ^3.3.2
  
  # 顶级 C++ 内核视频播放器 (降维打击抖音底层)
  media_kit: ^1.1.10
  media_kit_video: ^1.2.4
  media_kit_libs_video: ^1.0.7
  camera: ^0.12.0+1
  camera_windows: ^0.2.6+4
  video_player_win: ^3.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
